// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using WebbyWeb.Models;

namespace WebbyWeb.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20171121190722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("WebbyWeb.Models.Habit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("DoneOrNot");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ProfileId");

                    b.Property<string>("Time")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("ProfileId");

                    b.ToTable("Habit");
                });

            modelBuilder.Entity("WebbyWeb.Models.Profile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("WebbyWeb.Models.Habit", b =>
                {
                    b.HasOne("WebbyWeb.Models.Profile", "Profile")
                        .WithMany("Habits")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
